# This file is generated by cargo2nix 0.11.0.
# It may be regenerated at any time.
{
  workspace.dead-bot = {
    src = builtins.filterSource (name: type: type != "directory" || builtins.baseNameOf name != "target") ./.;
    crateBin = [
      {
        name = "dead-bot";
        path = "src/main.rs";
      }
    ];
    edition = "2021";
    version = "0.1.0";
  };
}