# This file contains settings for `cargo hakari`.
# See https://docs.rs/cargo-hakari/latest/cargo_hakari/config for a full list of options.

hakari-package = "dead-bot-workspace-hack"

# Format version for hakari's output. Version 4 requires cargo-hakari 0.9.22 or above.
dep-format-version = "4"

# Setting workspace.resolver = "2" in the root Cargo.toml is HIGHLY recommended.
# Hakari works much better with the new feature resolver.
resolver = "2"

# Add triples corresponding to platforms commonly used by developers here.
platforms = [
  "x86_64-unknown-linux-gnu", # Linux (your current platform)
  "x86_64-apple-darwin",      # macOS Intel
  "aarch64-apple-darwin",     # macOS Apple Silicon
  "x86_64-pc-windows-msvc",   # Windows
]

# Write out exact versions rather than a semver range for better reproducibility
exact-versions = true
